# This is a basic workflow to help you get started with Actions

name: arrive

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.2.0
        with:
          node-version: '14.x'

      # Runs a single command using the runners shell
      - name: idk
        run: npm install

      # Runs a set of commands using the runners shell
      - name: oof
        run: |
          echo something
          echo something else. lets stop editing this file
